# Use custom journald configuration parameters.
#
# @see journald.conf(5) for details.
# @see https://blog.stephane-robert.info/docs/admin-serveurs/linux/journalisation/

# In 'persistent' mode, journal logs are stored in '/var/log/journal' with a fallback to '/run/log/journal', during
# early boot and if the disk is not writable.
#
# Note that journald will initially use volatile storage (i.e. in '/run/log/journal'), until a call to
# 'journalctl --flush' (or using SIGUSR1 to journald) will cause it to switch to persistent logging.

[Journal]
Storage=persistent

SystemMaxUse=64M
SystemKeepFree=16M

RuntimeMaxUse=16M
RuntimeKeepFree=4M
