---
# @see https://linuxconfig.org/sendmail-unqualified-hostname-unknown-sleeping-for-retry-unqualified-hostname
- name: Configure the '/etc/hosts' file
  become: true
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '^127.0.1.1\s+.*$'
    replace: "127.0.1.1 {{ ansible_facts['nodename'] }}.homelab.internal {{ ansible_facts['nodename'] }}"
