---
- name: Install common Linux packages
  become: true
  ansible.builtin.package:
    name:
      # FIXME: Should be configurable from variables
      - cifs-utils
      - dnsutils
      - libsasl2-modules
      - logrotate
      - lynis
      - mailutils
      - rfkill
      - sysstat
      # Postfix requires specific configuration so it is installed in the '09-postfix.yml' file.
      #
      # - postfix
    state: latest

- name: Install additional Linux packages
  become: true
  ansible.builtin.package:
    name: "{{ packages | default([]) }}"
    state: latest
