# Gitlab CE
gitlab_email_from: "john.doe@example.com"
gitlab_external_url: "https://gitlab.homelab.internal"

# The wildcard TLS certificate for '*.homelab.internal'
tls:
  crt: "xxxxxxxx"
  key: "xxxxxxxx"

# HashiCorp Vault
vault_version: "1.21.2"
