# Gitlab CE
gitlab_email_from: "john.doe@example.com"
gitlab_tls_cert: "xxxxxxxx"
gitlab_tls_key: "xxxxxxxx"
gitlab_external_url: "https://gitlab.homelab.internal"

# HashiCorp Vault
vault_tls_cert: "xxxxxxxx"
vault_tls_key: "xxxxxxxx"
vault_version: "1.21.2"
