---
- hosts: pi-4
  roles:
    - role: common
      vars:
        network:
          host_aliases:
            - "gitlab.homelab.internal"
            - "vault.homelab.internal"
          ethernet:
            enabled: true
            mac_address: "{{ lookup('community.general.bitwarden', '5f23f062-c642-4c10-8c57-b3dc01505dd6', search='id', field='macAddress') | first }}"
            dhcp: false
            static:
              ip_address: "{{ lookup('community.general.bitwarden', '5f23f062-c642-4c10-8c57-b3dc01505dd6', search='id', field='ipAddress') | first }}"
    - role: pi-4
      vars:
        # Gitlab
        gitlab_email_from: "{{ lookup('community.general.bitwarden', '9c839a59-a7e4-4be9-88c7-b40500b6248c', search='id', field='smtpUsername') | first }}"
        gitlab_tls_cert: "{{ tls.crt }}"
        gitlab_tls_key: "{{ tls.key }}"
        # Hashicorp Vault
        vault_tls_cert: "{{ tls.crt }}"
        vault_tls_key: "{{ tls.key }}"
        vault_version: "1.21.2"
